services:
  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  scoring:
    build:
      context: ../services/scoring
    container_name: scoring
    environment:
      - DATASET_CSV_PATH=/app/data/datasets/pose_samples.csv
    volumes:
      - ../data/datasets:/app/data/datasets
    ports:
      - "8000:8000"

  api:
    build:
      context: ../apps/api
    container_name: api
    depends_on:
      - mongo
      - scoring
    env_file:
      - ../.env
    ports:
      - "3000:3000"

volumes:
  mongo_data:
